LabApp2/LabApp2/Models/ArticleViewModel.cs
namespace LabApp2.Models
{
    public class ArticleViewModel
    {
        public string Comment { get; set; }
    }
}

LabApp2/LabApp2/Models/ErrorViewModel.cs
namespace LabApp2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LabApp2/LabApp2/Components/CommentCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LabApp2.Components
{
    public class CommentCountViewComponent:ViewComponent
    {

            static int count=0;
            public IViewComponentResult Invoke(int CommentCount)
            {
                count++;
                return View("~/views/components/_CommentsCount.cshtml", count);
            }
        
    }
}

LabApp2/LabApp2/Components/CommentViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LabApp2.Components
{
    public class CommentViewComponent: ViewComponent
    {
        static List<string> comments = new List<string> { "First comment"};
        public IViewComponentResult Invoke(string NewComment)
        {
            if (NewComment != null)
            {
                comments.Add(new string (NewComment));
              
            }
            return View("~/views/components/_Comments.cshtml", comments);

        }
    }
}

LabApp2/LabApp2/Controllers/ArticleController.cs
using LabApp2.Models;
using Microsoft.AspNetCore.Mvc;

namespace LabApp2.Controllers
{
    public class ArticleController : Controller
    {
        public IActionResult Article()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OnAdd(ArticleViewModel model)
        {
            if (ModelState.IsValid)
            {

                if (model.Comment != null)
                {
                    ViewBag.AddedComment = model.Comment;
                }
                return View("Article");
            }
            else
            {
                return View("Article");
            }
        }
    }
}

LabApp2/LabApp2/Controllers/HomeController.cs
using LabApp2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LabApp2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LabApp2/LabApp2/Views/Article/Article.cshtml
@model LabApp2.Models.ArticleViewModel
@{
    ViewData["Title"] = "Article";

    string NewComment = ViewBag.AddedComment;
}

<h1>Article</h1>
<hr/>




<form asp-action="OnAdd" asp-controller="Article" method="post">

    <div>
        Enter Comment: <input type="text" asp-for="Comment"/>
    </div>
    <div>
        <input type="submit" value="Add Comment" />
    </div>

</form>

@await Component.InvokeAsync("Comment",NewComment)
@await Component.InvokeAsync("CommentCount")

LabApp2/LabApp2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>